/**
 * Robust Client-Side and Backend Download Helper
 */

export const resolveDownloadUrl = (url?: string | null): string | null => {
  if (!url || url === '#' || url === '') return null;
  if (url.startsWith('http://') || url.startsWith('https://') || url.startsWith('blob:')) {
    return url;
  }
  const backendBase = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
  return `${backendBase}${url.startsWith('/') ? '' : '/'}${url}`;
};

export const downloadPdfAdvisory = async (advisory: any, backendUrl?: string | null) => {
  const resolved = resolveDownloadUrl(backendUrl);

  if (resolved) {
    try {
      const response = await fetch(resolved);
      if (response.ok) {
        const blob = await response.blob();
        const blobUrl = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = blobUrl;
        a.download = `Advisory_${advisory?.title ? advisory.title.replace(/[^a-zA-Z0-9]/g, '_') : 'CHITRA'}.pdf`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(blobUrl);
        return;
      }
    } catch (e) {
      console.warn('Backend download failed, falling back to direct document generation:', e);
    }
  }

  // Pure Client-Side Fallback PDF/Document Generator
  const content = `
============================================================
              SECURITY ADVISORY // CHITRA
============================================================
Title: ${advisory?.title || 'Security Advisory'}
Severity: ${advisory?.severity || 'High'}
Classification: ${advisory?.classification_tier || 'PUBLIC'}
Date: ${advisory?.published_date || new Date().toISOString().split('T')[0]}
ID: ${advisory?.advisory_id || 'CHITRA-ADV-01'}
------------------------------------------------------------

1. WHAT HAPPENED (SUMMARY)
${advisory?.threat_overview || 'No summary available.'}

2. WHO / WHAT IS AFFECTED
${(advisory?.affected_systems || []).map((s: string) => `• ${s}`).join('\n')}

3. SIGNS TO LOOK FOR
${(advisory?.indicators_of_compromise || []).map((i: string) => `• ${i}`).join('\n')}

4. SIMPLE ACTION STEPS TO STAY SAFE
${(advisory?.mitigation_steps || []).map((m: string, idx: number) => `[${idx + 1}] ${m}`).join('\n')}

============================================================
Generated by CHITRA — Team NiTRO+
============================================================
`;

  const blob = new Blob([content], { type: 'application/pdf;charset=utf-8' });
  const blobUrl = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = blobUrl;
  a.download = `Security_Advisory_${(advisory?.title || 'CHITRA').slice(0, 30).replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(blobUrl);
};

export const downloadPptxDeck = async (title: string, backendUrl?: string | null) => {
  const resolved = resolveDownloadUrl(backendUrl);
  if (resolved) {
    try {
      const response = await fetch(resolved);
      if (response.ok) {
        const blob = await response.blob();
        const blobUrl = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = blobUrl;
        a.download = `Deck_${title.replace(/[^a-zA-Z0-9]/g, '_')}.pptx`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(blobUrl);
        return;
      }
    } catch (e) {
      console.warn('Backend PPTX download failed:', e);
    }
  }
};
